<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ShoppingCart.aspx.cs" Inherits="web1.ShoppingCart" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Shopping Cart</title>
    <style>
        body{
            background-size:cover; 
            background-image: url('背景圖.png'); 
            background-repeat: no-repeat; 
            background-attachment: fixed; 
            background-position: center center;

            font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
            color:#666;
        }

        h1{
            font-size:44px;
            padding:20px;
        }

        .divide{
            clear:both;
            font-size:36px;
        }
        .sure{
            font-size:22px;
            background-color: #663300;
            padding:10px;
            margin-right:auto;
            color: #fff;
            width: 160px;
        }

        .image{
            width:100px;
            height:100px;
            margin:10px;
        }

        .grid{
            margin-left:auto;
            margin-right:auto;
        }

        .cart{
            padding-top:10px;
        }
        .auto-style1 {
            font-size: large;
            color: #800000;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <h1>
            <asp:Image ID="Image3" runat="server" Height="50px" ImageAlign="Baseline" ImageUrl="~/shopping.png" Width="50px" CssClass="cart" />
            &nbsp;Shopping Cart</h1>
        <div style="float:left; width:70%">
            <asp:GridView ID="CartView" runat="server" AutoGenerateColumns="False" DataSourceID="CartDataSource" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="orderProduct_id" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="20" ForeColor="Black" GridLines="Horizontal" CssClass="grid" OnSelectedIndexChanged="CartView_SelectedIndexChanged" OnRowDataBound="CartView_RowDataBound" OnRowDeleted="CartView_RowDeleted">
                <Columns>
                    <asp:TemplateField HeaderText="商品圖片" SortExpression="product_img">
                        <EditItemTemplate>
                            <asp:Image ID="Image2" runat="server" ImageUrl='<%# Eval("product_img", "{0}") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("product_img") %>' />
                        </ItemTemplate>
                        <ControlStyle CssClass="image" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="商品名稱" SortExpression="product_name">
                        <EditItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Eval("product_name", "{0}") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("product_name") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="產品單價" SortExpression="product_price">
                        <EditItemTemplate>
                            <asp:Label ID="subtotalLB" runat="server" Text='<%# Eval("product_price", "{0:G}") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="subtotalLB" runat="server" Text='<%# Bind("product_price", "{0:G}") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="數量" SortExpression="num">
                        <EditItemTemplate>
                            <asp:TextBox ID="editNumLB" runat="server" Text='<%# Bind("num") %>' OnTextChanged="editNumLB_TextChanged"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="itemNumLB" runat="server" Text='<%# Bind("num") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="尺寸" SortExpression="size">
                        <EditItemTemplate>
                            <asp:DropDownList ID="SizeDropDown" runat="server" SelectedValue='<%# Bind("size", "{0}") %>'>
                                <asp:ListItem>XS</asp:ListItem>
                                <asp:ListItem>S</asp:ListItem>
                                <asp:ListItem>M</asp:ListItem>
                                <asp:ListItem>L</asp:ListItem>
                                <asp:ListItem>XL</asp:ListItem>
                                <asp:ListItem>XXL</asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("size") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="顏色" SortExpression="color">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ColorDropDown" runat="server" SelectedValue='<%# Bind("color", "{0}") %>'>
                                <asp:ListItem>Black</asp:ListItem>
                                <asp:ListItem>White</asp:ListItem>
                                <asp:ListItem>Grey</asp:ListItem>
                                <asp:ListItem>Yellow</asp:ListItem>
                                <asp:ListItem>Blue</asp:ListItem>
                                <asp:ListItem>Denim</asp:ListItem>
                                <asp:ListItem>Red</asp:ListItem>
                                <asp:ListItem>Pink</asp:ListItem>
                                <asp:ListItem>Purple</asp:ListItem>
                                <asp:ListItem>Dark Green</asp:ListItem>
                                <asp:ListItem>CUSTOM</asp:ListItem>
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("color") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="orderProduct_id" HeaderText="orderProduct_id" SortExpression="orderProduct_id" InsertVisible="False" ReadOnly="True" Visible="False" />
                </Columns>
                <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F7F7F7" />
                <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                <SortedDescendingCellStyle BackColor="#E5E5E5" />
                <SortedDescendingHeaderStyle BackColor="#242121" />
            </asp:GridView>
            
            
        </div>
        <div>
            <table>
                <tr>
                    <td>
                        <asp:Label ID="CartTotalPrice" runat="server" Text="Total : " CssClass="divide"></asp:Label>
                        <hr style:"font-bold:500" id="horizontalDiv" />
                    </td>
                    
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="PlaceOrder" runat="server" Text="Place Order" CssClass="sure" OnClick="PlaceOrder_Click" />
                    </td>
                    
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="BackToMain" runat="server" Text="Home" CssClass="sure" PostBackUrl="~/Default.aspx" />
                    </td>
                </tr>
            </table>
            
            
            
            
            
            <strong>
            
            
            
            
            
            <asp:Label ID="errorLB" runat="server" CssClass="auto-style1" Text="錯誤訊息" Visible="False"></asp:Label>
            
            
            </strong>
            
            
        </div>
        <asp:SqlDataSource ID="CartDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT productTable.product_name, orderProductTable.num, orderProductTable.size, orderProductTable.color, productTable.product_price, productTable.product_img, orderProductTable.orderProduct_id FROM orderProductTable INNER JOIN productTable ON orderProductTable.product_id = productTable.product_Id WHERE (orderProductTable.customer_id = @customer_id) AND (orderProductTable.paid = 0) ORDER BY productTable.product_class" DeleteCommand="DELETE FROM orderProductTable WHERE (orderProduct_id = @orderProduct_id)" UpdateCommand="UPDATE orderProductTable SET num = @num, size = @size, color = @color WHERE (orderProduct_id = @orderProduct_id)">
            <DeleteParameters>
                <asp:ControlParameter ControlID="CartView" Name="orderProduct_id" PropertyName="SelectedValue" />
            </DeleteParameters>
            <SelectParameters>
                <asp:SessionParameter Name="customer_id" SessionField="id" />
            </SelectParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="CartView" Name="num" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="CartView" Name="size" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="CartView" Name="color" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="CartView" Name="orderProduct_id" PropertyName="SelectedDataKey" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="QtDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT orderProductTable.product_id, orderProductTable.num, productTable.product_qt, orderProductTable.customer_id, orderProductTable.paid FROM orderProductTable INNER JOIN productTable ON orderProductTable.product_id = productTable.product_Id WHERE (orderProductTable.customer_id = @customer_id) AND (orderProductTable.paid = 0)" UpdateCommand="UPDATE productTable SET product_qt = @product_qt WHERE (product_Id = @product_Id)">
            <SelectParameters>
                <asp:SessionParameter Name="customer_id" SessionField="id" />
            </SelectParameters>
            <UpdateParameters>
                <asp:SessionParameter Name="product_qt" SessionField="updateQtNum" />
                <asp:SessionParameter Name="product_Id" SessionField="updateQtId" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:GridView ID="QtGridView" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataSourceID="QtDataSource" ForeColor="Black" GridLines="Vertical" Visible="False">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:TemplateField HeaderText="product_id" SortExpression="product_id">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("product_id") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="qtIdLB" runat="server" Text='<%# Bind("product_id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="num" SortExpression="num">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("num") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="itemNumLB" runat="server" Text='<%# Bind("num") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="product_qt" SortExpression="product_qt">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("product_qt") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="checkQtLB" runat="server" Text='<%# Bind("product_qt") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="customer_id" SortExpression="customer_id">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("customer_id") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("customer_id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>
    </form>
</body>
</html>
